# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7df060e79b986dd1e93f140569fc7a5d7e79e155ef27d0ea3b0bca98ab4559475427dd11721b82aa334049cd6c16be1a702265e80df3110689a89e141d17ee75

test:
  secret_key_base: 90e33eb98041c3507c8fded4121030e9575fe4e5a9973360443c8691fedf4b86ebdc9ea4a56b97243eca80e357509832ed0b57a0c9642becee23638d48d7cd27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
